from typing import Callable
import bpy
from .lib import addon
from .operator import a_simple_operator
from .operator import an_operator
from .operator import an_operator_with_a_uilist
from .menu import object_context as object_context_menu
from .panel import preferences as preferences_panel
from .panel import n_panel
from .panel import object_panel

if "_LOADED" in locals():
    import importlib

    for mod in (
    addon, a_simple_operator, an_operator, an_operator_with_a_uilist, object_context_menu, preferences_panel, n_panel,
    object_panel,):  # list all imports here
        importlib.reload(mod)
_LOADED = True

package_name = __package__

bl_info = {
    "name": "Untitled Blender Addon",
    "description": "Description goes here",
    "author": "Name goes here",
    "version": (0, 1, 0),
    "blender": (3, 4, 0),
    "location": "View3D > Object",
    "warning": "",  # used for warning icon and text in addons panel
    "doc_url": "https://github.com/{USERNAME}/{REPONAME}",
    "tracker_url": "https://github.com/{USERNAME}/{REPONAME}/issues",
    "support": "COMMUNITY",
    # Categories:
    # 3D View, Add Curve, Add Mesh, Animation, Compositing, Development, Game Engine, Import-Export, Lighting, Material,
    # Mesh, Node, Object, Paint, Physics, Render, Rigging, Scene, Sequencer, System, Text Editor, UV, User Interface
    "category": "Object",
}

menus: list[tuple[str, Callable]] = [
    # ("NODE_MT_context_menu", menu_function),
    # Some common ones:
    # "Object" menu
    # ("VIEW3D_MT_object", menu_function),
    # "Add" menu
    # ("VIEW3D_MT_add", menu_function),
    # "Add > Mesh" menu
    # ("VIEW3D_MT_mesh_add", menu_function),

    # Context (Spacebar/W) Menu
    ("VIEW3D_MT_object_context_menu",
     addon.menuitem(object_context_menu.UNTITLED_BLENDER_ADDON_MT_UntitledBlenderAddonSubmenu)),
    ("VIEW3D_MT_object_context_menu",
     addon.menuitem(an_operator.UNTITLED_BLENDER_ADDON_OT_AnOperator, 'INVOKE_DEFAULT')),

    # Some common ones:
    # "Object" menu
    # ("VIEW3D_MT_object", menu_function),
    # "Add" menu
    # ("VIEW3D_MT_add", menu_function),
    # "Add > Mesh" menu
    # ("VIEW3D_MT_mesh_add", menu_function),

    # Everything:
    # ("ASSETBROWSER_MT_context_menu", menu_function),
    # ("ASSETBROWSER_MT_edit", menu_function),
    # ("ASSETBROWSER_MT_editor_menus", menu_function),
    # ("ASSETBROWSER_MT_metadata_preview_menu", menu_function),
    # ("ASSETBROWSER_MT_select", menu_function),
    # ("ASSETBROWSER_MT_view", menu_function),
    # ("CLIP_MT_clip", menu_function),
    # ("CLIP_MT_marker_pie", menu_function),
    # ("CLIP_MT_masking_editor_menus", menu_function),
    # ("CLIP_MT_pivot_pie", menu_function),
    # ("CLIP_MT_plane_track_image_context_menu", menu_function),
    # ("CLIP_MT_proxy", menu_function),
    # ("CLIP_MT_reconstruction", menu_function),
    # ("CLIP_MT_reconstruction_pie", menu_function),
    # ("CLIP_MT_select", menu_function),
    # ("CLIP_MT_select_grouped", menu_function),
    # ("CLIP_MT_solving_pie", menu_function),
    # ("CLIP_MT_stabilize_2d_context_menu", menu_function),
    # ("CLIP_MT_stabilize_2d_rotation_context_menu", menu_function),
    # ("CLIP_MT_track", menu_function),
    # ("CLIP_MT_track_animation", menu_function),
    # ("CLIP_MT_track_cleanup", menu_function),
    # ("CLIP_MT_track_clear", menu_function),
    # ("CLIP_MT_track_motion", menu_function),
    # ("CLIP_MT_track_refine", menu_function),
    # ("CLIP_MT_track_transform", menu_function),
    # ("CLIP_MT_track_visibility", menu_function),
    # ("CLIP_MT_tracking_context_menu", menu_function),
    # ("CLIP_MT_tracking_editor_menus", menu_function),
    # ("CLIP_MT_tracking_pie", menu_function),
    # ("CLIP_MT_view", menu_function),
    # ("CLIP_MT_view_pie", menu_function),
    # ("CLIP_MT_view_zoom", menu_function),
    # ("COLLECTION_MT_context_menu", menu_function),
    # ("COLLECTION_MT_context_menu_instance_offset", menu_function),
    # ("CONSOLE_MT_console", menu_function),
    # ("CONSOLE_MT_context_menu", menu_function),
    # ("CONSOLE_MT_editor_menus", menu_function),
    # ("CONSOLE_MT_language", menu_function),
    # ("CONSOLE_MT_view", menu_function),
    # ("CURVES_MT_add_attribute", menu_function),
    # ("DATA_MT_bone_group_context_menu", menu_function),
    # ("DOPESHEET_MT_channel", menu_function),
    # ("DOPESHEET_MT_channel_context_menu", menu_function),
    # ("DOPESHEET_MT_context_menu", menu_function),
    # ("DOPESHEET_MT_delete", menu_function),
    # ("DOPESHEET_MT_editor_menus", menu_function),
    # ("DOPESHEET_MT_gpencil_channel", menu_function),
    # ("DOPESHEET_MT_gpencil_key", menu_function),
    # ("DOPESHEET_MT_key", menu_function),
    # ("DOPESHEET_MT_key_transform", menu_function),
    # ("DOPESHEET_MT_marker", menu_function),
    # ("DOPESHEET_MT_select", menu_function),
    # ("DOPESHEET_MT_snap_pie", menu_function),
    # ("DOPESHEET_MT_view", menu_function),
    # ("DOPESHEET_MT_view_pie", menu_function),
    # ("FILEBROWSER_MT_bookmarks_context_menu", menu_function),
    # ("FILEBROWSER_MT_context_menu", menu_function),
    # ("FILEBROWSER_MT_editor_menus", menu_function),
    # ("FILEBROWSER_MT_select", menu_function),
    # ("FILEBROWSER_MT_view", menu_function),
    # ("GPENCIL_MT_cleanup", menu_function),
    # ("GPENCIL_MT_gpencil_draw_delete", menu_function),
    # ("GPENCIL_MT_gpencil_vertex_group", menu_function),
    # ("GPENCIL_MT_layer_active", menu_function),
    # ("GPENCIL_MT_layer_context_menu", menu_function),
    # ("GPENCIL_MT_layer_mask_menu", menu_function),
    # ("GPENCIL_MT_material_active", menu_function),
    # ("GPENCIL_MT_material_context_menu", menu_function),
    # ("GPENCIL_MT_move_to_layer", menu_function),
    # ("GPENCIL_MT_snap", menu_function),
    # ("GPENCIL_MT_snap_pie", menu_function),
    # ("GRAPH_MT_channel", menu_function),
    # ("GRAPH_MT_channel_context_menu", menu_function),
    # ("GRAPH_MT_context_menu", menu_function),
    # ("GRAPH_MT_delete", menu_function),
    # ("GRAPH_MT_editor_menus", menu_function),
    # ("GRAPH_MT_key", menu_function),
    # ("GRAPH_MT_key_snap", menu_function),
    # ("GRAPH_MT_key_transform", menu_function),
    # ("GRAPH_MT_marker", menu_function),
    # ("GRAPH_MT_pivot_pie", menu_function),
    # ("GRAPH_MT_select", menu_function),
    # ("GRAPH_MT_slider", menu_function),
    # ("GRAPH_MT_snap_pie", menu_function),
    # ("GRAPH_MT_view", menu_function),
    # ("GRAPH_MT_view_pie", menu_function),
    # ("IMAGE_MT_editor_menus", menu_function),
    # ("IMAGE_MT_image", menu_function),
    # ("IMAGE_MT_image_flip", menu_function),
    # ("IMAGE_MT_image_invert", menu_function),
    # ("IMAGE_MT_mask_context_menu", menu_function),
    # ("IMAGE_MT_pivot_pie", menu_function),
    # ("IMAGE_MT_select", menu_function),
    # ("IMAGE_MT_select_linked", menu_function),
    # ("IMAGE_MT_uvs", menu_function),
    # ("IMAGE_MT_uvs_align", menu_function),
    # ("IMAGE_MT_uvs_context_menu", menu_function),
    # ("IMAGE_MT_uvs_merge", menu_function),
    # ("IMAGE_MT_uvs_mirror", menu_function),
    # ("IMAGE_MT_uvs_select_mode", menu_function),
    # ("IMAGE_MT_uvs_showhide", menu_function),
    # ("IMAGE_MT_uvs_snap", menu_function),
    # ("IMAGE_MT_uvs_snap_pie", menu_function),
    # ("IMAGE_MT_uvs_split", menu_function),
    # ("IMAGE_MT_uvs_transform", menu_function),
    # ("IMAGE_MT_uvs_unwrap", menu_function),
    # ("IMAGE_MT_view", menu_function),
    # ("IMAGE_MT_view_pie", menu_function),
    # ("IMAGE_MT_view_zoom", menu_function),
    # ("INFO_MT_area", menu_function),
    # ("INFO_MT_context_menu", menu_function),
    # ("INFO_MT_editor_menus", menu_function),
    # ("INFO_MT_info", menu_function),
    # ("INFO_MT_view", menu_function),
    # ("MASK_MT_add", menu_function),
    # ("MASK_MT_animation", menu_function),
    # ("MASK_MT_mask", menu_function),
    # ("MASK_MT_select", menu_function),
    # ("MASK_MT_transform", menu_function),
    # ("MASK_MT_visibility", menu_function),
    # ("MATERIAL_MT_context_menu", menu_function),
    # ("MESH_MT_attribute_context_menu", menu_function),
    # ("MESH_MT_color_attribute_context_menu", menu_function),
    # ("MESH_MT_shape_key_context_menu", menu_function),
    # ("MESH_MT_vertex_group_context_menu", menu_function),
    # ("NLA_MT_add", menu_function),
    # ("NLA_MT_channel_context_menu", menu_function),
    # ("NLA_MT_context_menu", menu_function),
    # ("NLA_MT_edit", menu_function),
    # ("NLA_MT_edit_transform", menu_function),
    # ("NLA_MT_editor_menus", menu_function),
    # ("NLA_MT_marker", menu_function),
    # ("NLA_MT_marker_select", menu_function),
    # ("NLA_MT_select", menu_function),
    # ("NLA_MT_snap_pie", menu_function),
    # ("NLA_MT_view", menu_function),
    # ("NLA_MT_view_pie", menu_function),
    # ("NODE_MT_add", menu_function),
    # ("NODE_MT_context_menu", menu_function),
    # ("NODE_MT_editor_menus", menu_function),
    # ("NODE_MT_node", menu_function),
    # ("NODE_MT_node_color_context_menu", menu_function),
    # ("NODE_MT_select", menu_function),
    # ("NODE_MT_view", menu_function),
    # ("NODE_MT_view_pie", menu_function),
    # ("OUTLINER_MT_asset", menu_function),
    # ("OUTLINER_MT_collection", menu_function),
    # ("OUTLINER_MT_collection_new", menu_function),
    # ("OUTLINER_MT_collection_view_layer", menu_function),
    # ("OUTLINER_MT_collection_visibility", menu_function),
    # ("OUTLINER_MT_context_menu", menu_function),
    # ("OUTLINER_MT_context_menu_view", menu_function),
    # ("OUTLINER_MT_edit_datablocks", menu_function),
    # ("OUTLINER_MT_editor_menus", menu_function),
    # ("OUTLINER_MT_object", menu_function),
    # ("OUTLINER_MT_view_pie", menu_function),
    # ("PARTICLE_MT_context_menu", menu_function),
    # ("POINTCLOUD_MT_add_attribute", menu_function),
    # ("RENDER_MT_framerate_presets", menu_function),
    # ("RENDER_MT_lineset_context_menu", menu_function),
    # ("SEQUENCER_MT_add", menu_function),
    # ("SEQUENCER_MT_add_effect", menu_function),
    # ("SEQUENCER_MT_add_empty", menu_function),
    # ("SEQUENCER_MT_add_scene", menu_function),
    # ("SEQUENCER_MT_add_transitions", menu_function),
    # ("SEQUENCER_MT_change", menu_function),
    # ("SEQUENCER_MT_color_tag_picker", menu_function),
    # ("SEQUENCER_MT_context_menu", menu_function),
    # ("SEQUENCER_MT_editor_menus", menu_function),
    # ("SEQUENCER_MT_image", menu_function),
    # ("SEQUENCER_MT_image_apply", menu_function),
    # ("SEQUENCER_MT_image_clear", menu_function),
    # ("SEQUENCER_MT_image_transform", menu_function),
    # ("SEQUENCER_MT_marker", menu_function),
    # ("SEQUENCER_MT_navigation", menu_function),
    # ("SEQUENCER_MT_pivot_pie", menu_function),
    # ("SEQUENCER_MT_preview_context_menu", menu_function),
    # ("SEQUENCER_MT_preview_view_pie", menu_function),
    # ("SEQUENCER_MT_preview_zoom", menu_function),
    # ("SEQUENCER_MT_proxy", menu_function),
    # ("SEQUENCER_MT_range", menu_function),
    # ("SEQUENCER_MT_select", menu_function),
    # ("SEQUENCER_MT_select_channel", menu_function),
    # ("SEQUENCER_MT_select_handle", menu_function),
    # ("SEQUENCER_MT_select_linked", menu_function),
    # ("SEQUENCER_MT_strip", menu_function),
    # ("SEQUENCER_MT_strip_effect", menu_function),
    # ("SEQUENCER_MT_strip_input", menu_function),
    # ("SEQUENCER_MT_strip_lock_mute", menu_function),
    # ("SEQUENCER_MT_strip_movie", menu_function),
    # ("SEQUENCER_MT_strip_transform", menu_function),
    # ("SEQUENCER_MT_view", menu_function),
    # ("SEQUENCER_MT_view_cache", menu_function),
    # ("SEQUENCER_MT_view_pie", menu_function),
    # ("TEXTURE_MT_context_menu", menu_function),
    # ("TEXT_MT_context_menu", menu_function),
    # ("TEXT_MT_edit", menu_function),
    # ("TEXT_MT_edit_to3d", menu_function),
    # ("TEXT_MT_editor_menus", menu_function),
    # ("TEXT_MT_format", menu_function),
    # ("TEXT_MT_select", menu_function),
    # ("TEXT_MT_templates", menu_function),
    # ("TEXT_MT_templates_osl", menu_function),
    # ("TEXT_MT_templates_py", menu_function),
    # ("TEXT_MT_text", menu_function),
    # ("TEXT_MT_view", menu_function),
    # ("TEXT_MT_view_navigation", menu_function),
    # ("TIME_MT_cache", menu_function),
    # ("TIME_MT_editor_menus", menu_function),
    # ("TIME_MT_marker", menu_function),
    # ("TIME_MT_view", menu_function),
    # ("TOPBAR_MT_blender", menu_function),
    # ("TOPBAR_MT_blender_system", menu_function),
    # ("TOPBAR_MT_edit", menu_function),
    # ("TOPBAR_MT_edit_armature_add", menu_function),
    # ("TOPBAR_MT_edit_curve_add", menu_function),
    # ("TOPBAR_MT_editor_menus", menu_function),
    # ("TOPBAR_MT_file", menu_function),
    # ("TOPBAR_MT_file_cleanup", menu_function),
    # ("TOPBAR_MT_file_context_menu", menu_function),
    # ("TOPBAR_MT_file_defaults", menu_function),
    # ("TOPBAR_MT_file_export", menu_function),
    # ("TOPBAR_MT_file_external_data", menu_function),
    # ("TOPBAR_MT_file_import", menu_function),
    # ("TOPBAR_MT_file_new", menu_function),
    # ("TOPBAR_MT_file_previews", menu_function),
    # ("TOPBAR_MT_file_recover", menu_function),
    # ("TOPBAR_MT_help", menu_function),
    # ("TOPBAR_MT_render", menu_function),
    # ("TOPBAR_MT_templates_more", menu_function),
    # ("TOPBAR_MT_window", menu_function),
    # ("TOPBAR_MT_workspace_menu", menu_function),
    # ("UI_MT_list_item_context_menu", menu_function),
    # ("USERPREF_MT_editor_menus", menu_function),
    # ("USERPREF_MT_interface_theme_presets", menu_function),
    # ("USERPREF_MT_keyconfigs", menu_function),
    # ("USERPREF_MT_save_load", menu_function),
    # ("USERPREF_MT_view", menu_function),
    # ("VIEW3D_MT_add", menu_function),
    # ("VIEW3D_MT_angle_control", menu_function),
    # ("VIEW3D_MT_armature_add", menu_function),
    # ("VIEW3D_MT_armature_context_menu", menu_function),
    # ("VIEW3D_MT_assign_material", menu_function),
    # ("VIEW3D_MT_bone_options_disable", menu_function),
    # ("VIEW3D_MT_bone_options_enable", menu_function),
    # ("VIEW3D_MT_bone_options_toggle", menu_function),
    # ("VIEW3D_MT_brush_context_menu", menu_function),
    # ("VIEW3D_MT_brush_context_menu_paint_modes", menu_function),
    # ("VIEW3D_MT_brush_gpencil_context_menu", menu_function),
    # ("VIEW3D_MT_brush_paint_modes", menu_function),
    # ("VIEW3D_MT_camera_add", menu_function),
    # ("VIEW3D_MT_curve_add", menu_function),
    # ("VIEW3D_MT_draw_gpencil", menu_function),
    # ("VIEW3D_MT_edit_armature", menu_function),
    # ("VIEW3D_MT_edit_armature_delete", menu_function),
    # ("VIEW3D_MT_edit_armature_names", menu_function),
    # ("VIEW3D_MT_edit_armature_parent", menu_function),
    # ("VIEW3D_MT_edit_armature_roll", menu_function),
    # ("VIEW3D_MT_edit_curve", menu_function),
    # ("VIEW3D_MT_edit_curve_clean", menu_function),
    # ("VIEW3D_MT_edit_curve_context_menu", menu_function),
    # ("VIEW3D_MT_edit_curve_ctrlpoints", menu_function),
    # ("VIEW3D_MT_edit_curve_delete", menu_function),
    # ("VIEW3D_MT_edit_curve_segments", menu_function),
    # ("VIEW3D_MT_edit_curve_showhide", menu_function),
    # ("VIEW3D_MT_edit_curves", menu_function),
    # ("VIEW3D_MT_edit_font", menu_function),
    # ("VIEW3D_MT_edit_font_chars", menu_function),
    # ("VIEW3D_MT_edit_font_context_menu", menu_function),
    # ("VIEW3D_MT_edit_font_delete", menu_function),
    # ("VIEW3D_MT_edit_font_kerning", menu_function),
    # ("VIEW3D_MT_edit_gpencil", menu_function),
    # ("VIEW3D_MT_edit_gpencil_delete", menu_function),
    # ("VIEW3D_MT_edit_gpencil_point", menu_function),
    # ("VIEW3D_MT_edit_gpencil_showhide", menu_function),
    # ("VIEW3D_MT_edit_gpencil_stroke", menu_function),
    # ("VIEW3D_MT_edit_gpencil_transform", menu_function),
    # ("VIEW3D_MT_edit_lattice", menu_function),
    # ("VIEW3D_MT_edit_lattice_context_menu", menu_function),
    # ("VIEW3D_MT_edit_mesh", menu_function),
    # ("VIEW3D_MT_edit_mesh_clean", menu_function),
    # ("VIEW3D_MT_edit_mesh_context_menu", menu_function),
    # ("VIEW3D_MT_edit_mesh_delete", menu_function),
    # ("VIEW3D_MT_edit_mesh_edges", menu_function),
    # ("VIEW3D_MT_edit_mesh_extrude", menu_function),
    # ("VIEW3D_MT_edit_mesh_faces", menu_function),
    # ("VIEW3D_MT_edit_mesh_faces_data", menu_function),
    # ("VIEW3D_MT_edit_mesh_merge", menu_function),
    # ("VIEW3D_MT_edit_mesh_normals", menu_function),
    # ("VIEW3D_MT_edit_mesh_normals_average", menu_function),
    # ("VIEW3D_MT_edit_mesh_normals_select_strength", menu_function),
    # ("VIEW3D_MT_edit_mesh_normals_set_strength", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_by_trait", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_linked", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_loops", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_mode", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_more_less", menu_function),
    # ("VIEW3D_MT_edit_mesh_select_similar", menu_function),
    # ("VIEW3D_MT_edit_mesh_shading", menu_function),
    # ("VIEW3D_MT_edit_mesh_showhide", menu_function),
    # ("VIEW3D_MT_edit_mesh_split", menu_function),
    # ("VIEW3D_MT_edit_mesh_vertices", menu_function),
    # ("VIEW3D_MT_edit_mesh_weights", menu_function),
    # ("VIEW3D_MT_edit_meta", menu_function),
    # ("VIEW3D_MT_edit_meta_showhide", menu_function),
    # ("VIEW3D_MT_edit_metaball_context_menu", menu_function),
    # ("VIEW3D_MT_edit_surface", menu_function),
    # ("VIEW3D_MT_editor_menus", menu_function),
    # ("VIEW3D_MT_face_sets", menu_function),
    # ("VIEW3D_MT_face_sets_init", menu_function),
    # ("VIEW3D_MT_gpencil_animation", menu_function),
    # ("VIEW3D_MT_gpencil_autoweights", menu_function),
    # ("VIEW3D_MT_gpencil_edit_context_menu", menu_function),
    # ("VIEW3D_MT_gpencil_simplify", menu_function),
    # ("VIEW3D_MT_gpencil_vertex_group", menu_function),
    # ("VIEW3D_MT_hook", menu_function),
    # ("VIEW3D_MT_image_add", menu_function),
    # ("VIEW3D_MT_light_add", menu_function),
    # ("VIEW3D_MT_lightprobe_add", menu_function),
    # ("VIEW3D_MT_make_links", menu_function),
    # ("VIEW3D_MT_make_single_user", menu_function),
    # ("VIEW3D_MT_mask", menu_function),
    # ("VIEW3D_MT_mesh_add", menu_function),
    # ("VIEW3D_MT_metaball_add", menu_function),
    # ("VIEW3D_MT_mirror", menu_function),
    # ("VIEW3D_MT_object", menu_function),
    # ("VIEW3D_MT_object_animation", menu_function),
    # ("VIEW3D_MT_object_apply", menu_function),
    # ("VIEW3D_MT_object_asset", menu_function),
    # ("VIEW3D_MT_object_cleanup", menu_function),
    # ("VIEW3D_MT_object_clear", menu_function),
    # ("VIEW3D_MT_object_collection", menu_function),
    # ("VIEW3D_MT_object_constraints", menu_function),
    # ("VIEW3D_MT_object_context_menu", menu_function),
    # ("VIEW3D_MT_object_convert", menu_function),
    # ("VIEW3D_MT_object_mode_pie", menu_function),
    # ("VIEW3D_MT_object_parent", menu_function),
    # ("VIEW3D_MT_object_quick_effects", menu_function),
    # ("VIEW3D_MT_object_relations", menu_function),
    # ("VIEW3D_MT_object_rigid_body", menu_function),
    # ("VIEW3D_MT_object_shading", menu_function),
    # ("VIEW3D_MT_object_showhide", menu_function),
    # ("VIEW3D_MT_object_track", menu_function),
    # ("VIEW3D_MT_orientations_pie", menu_function),
    # ("VIEW3D_MT_paint_gpencil", menu_function),
    # ("VIEW3D_MT_paint_vertex", menu_function),
    # ("VIEW3D_MT_paint_weight", menu_function),
    # ("VIEW3D_MT_paint_weight_lock", menu_function),
    # ("VIEW3D_MT_particle", menu_function),
    # ("VIEW3D_MT_particle_context_menu", menu_function),
    # ("VIEW3D_MT_particle_showhide", menu_function),
    # ("VIEW3D_MT_pivot_pie", menu_function),
    # ("VIEW3D_MT_pose", menu_function),
    # ("VIEW3D_MT_pose_apply", menu_function),
    # ("VIEW3D_MT_pose_constraints", menu_function),
    # ("VIEW3D_MT_pose_context_menu", menu_function),
    # ("VIEW3D_MT_pose_group", menu_function),
    # ("VIEW3D_MT_pose_ik", menu_function),
    # ("VIEW3D_MT_pose_motion", menu_function),
    # ("VIEW3D_MT_pose_names", menu_function),
    # ("VIEW3D_MT_pose_propagate", menu_function),
    # ("VIEW3D_MT_pose_showhide", menu_function),
    # ("VIEW3D_MT_pose_slide", menu_function),
    # ("VIEW3D_MT_pose_transform", menu_function),
    # ("VIEW3D_MT_proportional_editing_falloff_pie", menu_function),
    # ("VIEW3D_MT_random_mask", menu_function),
    # ("VIEW3D_MT_sculpt", menu_function),
    # ("VIEW3D_MT_sculpt_automasking_pie", menu_function),
    # ("VIEW3D_MT_sculpt_curves", menu_function),
    # ("VIEW3D_MT_sculpt_face_sets_edit_pie", menu_function),
    # ("VIEW3D_MT_sculpt_mask_edit_pie", menu_function),
    # ("VIEW3D_MT_sculpt_set_pivot", menu_function),
    # ("VIEW3D_MT_select_edit_armature", menu_function),
    # ("VIEW3D_MT_select_edit_curve", menu_function),
    # ("VIEW3D_MT_select_edit_curves", menu_function),
    # ("VIEW3D_MT_select_edit_lattice", menu_function),
    # ("VIEW3D_MT_select_edit_mesh", menu_function),
    # ("VIEW3D_MT_select_edit_metaball", menu_function),
    # ("VIEW3D_MT_select_edit_surface", menu_function),
    # ("VIEW3D_MT_select_edit_text", menu_function),
    # ("VIEW3D_MT_select_gpencil", menu_function),
    # ("VIEW3D_MT_select_object", menu_function),
    # ("VIEW3D_MT_select_object_more_less", menu_function),
    # ("VIEW3D_MT_select_paint_mask", menu_function),
    # ("VIEW3D_MT_select_paint_mask_vertex", menu_function),
    # ("VIEW3D_MT_select_particle", menu_function),
    # ("VIEW3D_MT_select_pose", menu_function),
    # ("VIEW3D_MT_select_pose_more_less", menu_function),
    # ("VIEW3D_MT_select_sculpt_curves", menu_function),
    # ("VIEW3D_MT_shading_ex_pie", menu_function),
    # ("VIEW3D_MT_shading_pie", menu_function),
    # ("VIEW3D_MT_snap", menu_function),
    # ("VIEW3D_MT_snap_pie", menu_function),
    # ("VIEW3D_MT_surface_add", menu_function),
    # ("VIEW3D_MT_tools_projectpaint_clone", menu_function),
    # ("VIEW3D_MT_tools_projectpaint_stencil", menu_function),
    # ("VIEW3D_MT_tools_projectpaint_uvlayer", menu_function),
    # ("VIEW3D_MT_transform", menu_function),
    # ("VIEW3D_MT_transform_armature", menu_function),
    # ("VIEW3D_MT_transform_gizmo_pie", menu_function),
    # ("VIEW3D_MT_transform_object", menu_function),
    # ("VIEW3D_MT_uv_map", menu_function),
    # ("VIEW3D_MT_vertex_group", menu_function),
    # ("VIEW3D_MT_view", menu_function),
    # ("VIEW3D_MT_view_align", menu_function),
    # ("VIEW3D_MT_view_align_selected", menu_function),
    # ("VIEW3D_MT_view_cameras", menu_function),
    # ("VIEW3D_MT_view_local", menu_function),
    # ("VIEW3D_MT_view_navigation", menu_function),
    # ("VIEW3D_MT_view_pie", menu_function),
    # ("VIEW3D_MT_view_regions", menu_function),
    # ("bpy.types", menu_function),
    # ("VIEW3D_MT_volume_add", menu_function),
    # ("VIEW3D_MT_weight_gpencil", menu_function),
    # ("VIEW3D_MT_wpaint_vgroup_lock_pie", menu_function),
    # ("VIEWLAYER_MT_lightgroup_sync", menu_function),
    # ("WM_MT_operator_presets", menu_function),
    # ("WM_MT_splash", menu_function),
    # ("WM_MT_splash_about", menu_function),
    # ("WM_MT_splash_quick_setup", menu_function),
    # ("WM_MT_toolsystem_submenu", menu_function),
]

# Registerable modules have a REGISTER_CLASSES list that lists all registerable classes in the module
registerable_modules = [
    a_simple_operator,
    an_operator,
    an_operator_with_a_uilist,
    object_context_menu,
    preferences_panel,
    n_panel,
    object_panel,
]


def register() -> None:
    for c in addon.get_registerable_classes(registerable_modules):
        # Attempt to clean up if the addon broke during registration.
        try:
            bpy.utils.unregister_class(c)
        except RuntimeError:
            pass
        bpy.utils.register_class(c)
        if hasattr(c, 'post_register') and callable(c.post_register):
            c.post_register()
        print("Untitled Blender Addon registered class:", c)
    addon.register_menus(menus)


def unregister() -> None:
    addon.unregister_menus(menus)
    for m in menus[::-1]:
        getattr(bpy.types, m[0]).remove(m[1])
    for c in addon.get_registerable_classes(registerable_modules)[::-1]:
        try:
            bpy.utils.unregister_class(c)
            if hasattr(c, 'post_unregister') and callable(c.post_unregister):
                c.post_unregister()
        except RuntimeError:
            pass


if __name__ == "__main__":
    register()
